name: qBitRemote
description: A new Flutter project.

publish_to: 'none'

version: 0.4.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  cupertino_icons: ^1.0.2
  supercharged: ^1.12.0

  # architecture
  flutter_bloc: ^6.1.1

  provider: ^4.3.2+4
  path_provider: ^1.6.27
  dio: ^3.0.10
  dio_cookie_manager: 1.0.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  toggle_switch: ^0.1.8
  file_picker: ^2.1.5+1
  string_validator: ^0.1.4
  focus_detector: ^1.1.0+1
  package_info: ^0.4.3+2
  tree_view: ^0.0.5
  freezed_annotation: ^0.12.0

  #analitics
  firebase_analytics: ^7.0.1

#dependency_overrides:
# path: 1.7.0
# dartx: ">=0.2.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.13
  freezed: ^0.12.7

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
