name: qBitRemote
description: A new Flutter project.

publish_to: 'none'

version: 0.12.0+10

environment:
  sdk: ">=2.14.4 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # architecture
  flutter_bloc: ^8.0.0
  provider: ^6.0.1
  # file
  path_provider: ^2.0.8
  file_picker: ^4.2.8
  # analitics
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_crashlytics: ^2.4.4
  # ui
  toggle_switch: ^1.3.0
  focus_detector: ^2.0.0
  # other
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  string_validator: ^0.3.0
  package_info: ^2.0.2
  freezed_annotation: ^1.1.0
  url_launcher: ^6.0.17
  get_it: ^7.2.0
  cupertino_icons: ^1.0.4
  supercharged: ^2.1.1
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.5
  freezed: ^1.1.0

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
