name: qBitRemote
description: A new Flutter project.

publish_to: 'none'

version: 0.7.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # architecture
  flutter_bloc: ^6.1.2
  provider: ^4.3.3
  # file
  path_provider: ^1.6.27
  file_picker: ^2.1.6
  # analitics
  firebase_analytics: ^7.0.1
  # ui
  toggle_switch: ^0.1.8
  focus_detector: ^1.1.0+1
  tree_view: ^0.0.5
  # other
  dio: ^3.0.10
  dio_cookie_manager: 1.0.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  string_validator: ^0.1.4
  package_info: ^2.0.0
  freezed_annotation: ^0.12.0
  url_launcher: ^6.0.0-nullsafety.6
  get_it: ^6.0.0
  cupertino_icons: ^1.0.2
  supercharged: ^1.12.0

#dependency_overrides:
# path: 1.7.0
# dartx: ">=0.2.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.11.5
  freezed: ^0.12.7

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
